trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: DotNetCoreCLI@2
  name: Restore
  inputs:
    command: 'restore'
    projects: '''**/*.csproj'''
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  name: Pack
  inputs:
    command: 'pack'
    packagesToPack: 
    versioningScheme: 'off'
    verbosityPack: Quiet

- task: NuGetCommand@2
  name: Publish
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'Guncharted-NuGet'
    allowPackageConflicts: true
