trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: DotNetCoreCLI@2
  name: Restore
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  name: Pack
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versioningScheme: 'off'
    verbosityPack: Quiet

# - task: NuGetCommand@2
#   name: Publish
#   inputs:
#     command: 'push'
#     packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
#     nuGetFeedType: 'external'
#     publishFeedCredentials: 'Guncharted-NuGet'
#     allowPackageConflicts: true

- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'
- script: nuget push $(Build.ArtifactStagingDirectory)\*.*.nupkg -Source $(nugetSource) -ApiKey $(nuget.apikey) -SkipDuplicate -NoSymbols
  displayName: 'Push to NuGet.org'
    
